name: dartt
description: A sample dartt application.
version: 1.0.0
homepage: https://github.com/singcl/dartt
author: singcl<iambabyer@gmail.com>

environment:
    sdk: '>=2.1.0 <3.0.0'

dependencies:
    vector_math: ^2.0.7

dev_dependencies:
    pedantic: ^1.0.0
    test: ^1.0.0
