name: vector_victor
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: singcl <email@example.com>

environment:
    sdk: '>=2.1.0 <3.0.0'

dependencies:
    vector_math: ^2.0.7

dev_dependencies:
    pedantic: ^1.0.0
    test: ^1.0.0
